'use strict';

const fs = require('fs');
const os = require('os');
const path = require('path');

const {
  parseReleaseEnv,
  releaseInfoFromEnv,
  readReleaseInfo,
} = require('../lib/release-info');

function tmpDir() {
  return fs.mkdtempSync(path.join(os.tmpdir(), 'planner-release-info-'));
}

describe('release-info parser', () => {
  test('parseReleaseEnv: comments and blank lines are ignored', () => {
    const txt = [
      '# Auto-generated by deploy.sh — do not edit.',
      '',
      'DEPLOY_VERSION=f602951f',
      '   ',
      '# another comment',
      'DEPLOY_TIMESTAMP=20260415-071647',
      'DEPLOY_BRANCH=main',
      'DEPLOYED_AT=2026-04-15T07:16:53Z',
    ].join('\n');
    const env = parseReleaseEnv(txt);
    expect(env.DEPLOY_VERSION).toBe('f602951f');
    expect(env.DEPLOY_TIMESTAMP).toBe('20260415-071647');
    expect(env.DEPLOY_BRANCH).toBe('main');
    expect(env.DEPLOYED_AT).toBe('2026-04-15T07:16:53Z');
  });

  test('releaseInfoFromEnv: all three keys present -> populated object', () => {
    const info = releaseInfoFromEnv({
      DEPLOY_VERSION: 'abc1234',
      DEPLOY_TIMESTAMP: '20260101-000000',
      DEPLOY_BRANCH: 'main',
    });
    expect(info).toEqual({
      branch: 'main',
      sha: 'abc1234',
      timestamp: '20260101-000000',
    });
  });

  test('releaseInfoFromEnv: missing DEPLOY_VERSION -> null', () => {
    const info = releaseInfoFromEnv({
      DEPLOY_TIMESTAMP: '20260101-000000',
      DEPLOY_BRANCH: 'main',
    });
    expect(info).toBeNull();
  });

  test('releaseInfoFromEnv: empty DEPLOY_BRANCH -> null', () => {
    const info = releaseInfoFromEnv({
      DEPLOY_VERSION: 'abc1234',
      DEPLOY_TIMESTAMP: '20260101-000000',
      DEPLOY_BRANCH: '',
    });
    expect(info).toBeNull();
  });
});

describe('readReleaseInfo (filesystem)', () => {
  test('file missing -> null', () => {
    const dir = tmpDir();
    expect(readReleaseInfo(dir)).toBeNull();
  });

  test('file present with all 3 keys -> populated object', () => {
    const dir = tmpDir();
    fs.writeFileSync(
      path.join(dir, 'release.env'),
      [
        '# auto-generated',
        'DEPLOY_VERSION=f602951f',
        'DEPLOY_TIMESTAMP=20260415-071647',
        'DEPLOY_BRANCH=main',
        'DEPLOYED_AT=2026-04-15T07:16:53Z',
      ].join('\n'),
    );
    expect(readReleaseInfo(dir)).toEqual({
      branch: 'main',
      sha: 'f602951f',
      timestamp: '20260415-071647',
    });
  });

  test('file present but missing DEPLOY_VERSION -> null', () => {
    const dir = tmpDir();
    fs.writeFileSync(
      path.join(dir, 'release.env'),
      [
        'DEPLOY_TIMESTAMP=20260415-071647',
        'DEPLOY_BRANCH=main',
      ].join('\n'),
    );
    expect(readReleaseInfo(dir)).toBeNull();
  });

  test('file present with comments and empty lines -> parses correctly', () => {
    const dir = tmpDir();
    fs.writeFileSync(
      path.join(dir, 'release.env'),
      [
        '# Auto-generated by deploy.sh',
        '',
        '   ',
        'DEPLOY_VERSION=abc1234',
        '# mid comment',
        'DEPLOY_TIMESTAMP=20260101-000000',
        'DEPLOY_BRANCH=main',
        '',
      ].join('\n'),
    );
    expect(readReleaseInfo(dir)).toEqual({
      branch: 'main',
      sha: 'abc1234',
      timestamp: '20260101-000000',
    });
  });
});
