'use strict';

/*
 * release-info.js
 *
 * Reads the `release.env` file the deploy pipeline writes into the release
 * directory (see infrastructure/common/lib.sh :: write_release_metadata). The
 * file looks like:
 *
 *   # Auto-generated by deploy.sh — do not edit. Overwritten on every deploy.
 *   DEPLOY_VERSION=f602951f
 *   DEPLOY_TIMESTAMP=20260415-071647
 *   DEPLOY_BRANCH=main
 *   DEPLOYED_AT=2026-04-15T07:16:53Z
 *
 * If the file exists AND contains non-empty DEPLOY_VERSION, DEPLOY_TIMESTAMP
 * and DEPLOY_BRANCH, `readReleaseInfo()` returns:
 *
 *   { branch, sha, timestamp }
 *
 * In all other cases (missing file, missing key, empty value) it returns
 * `null`. The settings UI treats `null` as "hide the deploy line entirely".
 * This matches Dirk's hard requirement: never render "unknown"/"n/a".
 */

const fs = require('fs');
const path = require('path');

function parseReleaseEnv(text) {
  const out = {};
  if (typeof text !== 'string') return out;
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq <= 0) continue;
    const key = line.slice(0, eq).trim();
    let val = line.slice(eq + 1).trim();
    // Strip optional surrounding quotes
    if ((val.startsWith('"') && val.endsWith('"')) ||
        (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    out[key] = val;
  }
  return out;
}

function releaseInfoFromEnv(env) {
  if (!env) return null;
  const branch = env.DEPLOY_BRANCH;
  const sha = env.DEPLOY_VERSION;
  const timestamp = env.DEPLOY_TIMESTAMP;
  if (!branch || !sha || !timestamp) return null;
  return { branch, sha, timestamp };
}

function readReleaseInfo(cwd) {
  const dir = cwd || process.cwd();
  const file = path.join(dir, 'release.env');
  let text;
  try {
    text = fs.readFileSync(file, 'utf8');
  } catch (err) {
    if (err && err.code === 'ENOENT') return null;
    // Any other read error: behave as if missing. We do not want a broken
    // release.env to crash the app.
    return null;
  }
  return releaseInfoFromEnv(parseReleaseEnv(text));
}

module.exports = { parseReleaseEnv, releaseInfoFromEnv, readReleaseInfo };
